### ISSUE TITLE
messages not appearing / not sending

### ISSUE THREAD

**Issue by DrN1ghtW0lf** [OrnitOnGithub/lan-chatroom#10]
My messages are not appearing when i send them

**Comment by OrnitOnGithub** [comment]
This is not helpful. Please provide more details and any errors that may appear in the terminal, or any information that may help me recreate the error, like:
- your settings.json file
- what messages you're sending
- wether you're on the latest version
- Your machine / python version

Normal reasons you may not recieve a message:
- Illegal format (you messed with the code)
- Reserved port number
- Your encryption key if it's not confidential.

When reporting an error provide steps on how to recreate it. Thank you. Especially since nobody has had this issue yet.

**Comment by OrnitOnGithub** [comment]
Actually, this issue is from this morning. If I recall correctly, we tested on port 55554 which is a reserved port. That explains the error.
